### ISSUE TITLE
key_ and others are gone

### ISSUE THREAD

**Issue by mexx** [xyncro/aether#40]
d8b05fbd51a86b2a348e5cb323834e06f86f7461 removed them without providing `Obsolete` warning

**Comment by mexx** [comment]
I also get 
```The module/namespace 'Aether' from compilation unit 'Aether' did not contain the namespace, module or type 'PLens`2'``` message, as this type was renamed to `Prism`

**Comment by mexx** [comment]
`PLens` was used by the an old version `5.2.1` of Chiron, an update to `6.0.1` fixed my problem, but nevertheless would break code without `Obsolete` warning.

**Comment by kolektiv** [comment]
Yes, this is from an unfortunate point in history where I hadn't decided on a policy for backward compatibility. Aether has gone through a major version (or two perhaps) since and I think that all "latest" versions of libraries in the wild that use Aether directly either have a pinned version, or work with current Aether.

Bit of a learning experience with these ones - I'm not sure that going back and adding obsoletes now has much value over getting people to upgrade, but if you think it's worth doing now, I'm open to doing so!

**Comment by mexx** [comment]
I have a relatively small code base, but it caused pain as I only wanted to have use new features.
I know I have to handle the obsoletes someday but with them in place I could schedule it at some point where I have no pressure. If I'm the only user, then we don't have to provide them.

**Comment by kolektiv** [comment]
Yes, that's fair enough. I don't think you're the only user :) I'll look at
adding things as backwards compatible.
